// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeQ2AhXLzJKnZFHXNNJJ4i_BoAVy99FUE',
    appId: '1:723339825562:web:0c12d00c94342d43dfea23',
    messagingSenderId: '723339825562',
    projectId: 'smart-hydroponic-f060f',
    authDomain: 'smart-hydroponic-f060f.firebaseapp.com',
    storageBucket: 'smart-hydroponic-f060f.firebasestorage.app',
    measurementId: 'G-65SGHR46VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyUb7duPfFHHz798TCE5FDlmas6SB0jSs',
    appId: '1:723339825562:android:6da69960250d27bfdfea23',
    messagingSenderId: '723339825562',
    projectId: 'smart-hydroponic-f060f',
    storageBucket: 'smart-hydroponic-f060f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzTIa8z7oyvkDaMU-I46rHZvoMk93El-U',
    appId: '1:723339825562:ios:cde6e7854526cbf6dfea23',
    messagingSenderId: '723339825562',
    projectId: 'smart-hydroponic-f060f',
    storageBucket: 'smart-hydroponic-f060f.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzTIa8z7oyvkDaMU-I46rHZvoMk93El-U',
    appId: '1:723339825562:ios:cde6e7854526cbf6dfea23',
    messagingSenderId: '723339825562',
    projectId: 'smart-hydroponic-f060f',
    storageBucket: 'smart-hydroponic-f060f.firebasestorage.app',
    iosBundleId: 'com.example.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeQ2AhXLzJKnZFHXNNJJ4i_BoAVy99FUE',
    appId: '1:723339825562:web:16117a2c133f8586dfea23',
    messagingSenderId: '723339825562',
    projectId: 'smart-hydroponic-f060f',
    authDomain: 'smart-hydroponic-f060f.firebaseapp.com',
    storageBucket: 'smart-hydroponic-f060f.firebasestorage.app',
    measurementId: 'G-EQM44DE7J9',
  );
}
